/**
 * js/i18n.js — Interruptor de idioma ES/EN para toda la interfaz
 * ─────────────────────────────────────────────────────────────────────────────
 * Traduce TODO el contenido de la app (chrome + vistas profundas) mediante un
 * diccionario de strings exactos. El español es el idioma fuente; en EN se
 * reemplazan los nodos de texto cuyo contenido coincide con el diccionario.
 *
 * Usar MutationObserver para detectar cambios dinámicos y re-aplicar la
 * traducción automáticamente cuando el contenido cambia.
 *
 * API pública: window.i18n = { get(), set(lang), apply() }
 */
(function () {
  'use strict';

  var LS_KEY = 'predictable_lang';
  var observer = null;

  // Diccionario ES → EN (toda la interfaz, strings exactos tras trim).
  var ES_EN = {
    // Sidebar — secciones
    'Operar': 'Operate',
    'Inteligencia': 'Intelligence',
    'Ejecutar': 'Execute',
    'Aprender': 'Learn',
    // Sidebar — items
    'Dashboard': 'Dashboard',
    'Radar': 'Radar',
    'Clients': 'Clients',
    'Prospección': 'Prospecting',
    'Search People': 'Search People',
    'Listas guardadas': 'Saved lists',
    'Contactos': 'Contacts',
    'Secuencias': 'Sequences',
    'Generador de mensajes IA': 'AI message generator',
    'Bandeja': 'Inbox',
    'Inbox WhatsApp': 'WhatsApp Inbox',
    'Plantillas': 'Templates',
    'Ventas AI': 'Sales AI',
    'Meeting Coach': 'Meeting Coach',
    'Reportes': 'Reports',
    'Mi rendimiento': 'My performance',
    // Sidebar — footer
    'Primeros pasos': 'Getting started',
    'Claro': 'Light',
    'Oscuro': 'Dark',
    'ES · Español': 'ES · Spanish',
    'EN · English': 'EN · English',
    'Ajustes': 'Settings',
    'Cerrar sesión': 'Log out',
    // Dashboard
    'Revenue OS': 'Revenue OS',
    'Tu operación de revenue, en un vistazo': 'Your revenue operation, at a glance',
    // Dashboard — KPIs
    'Reuniones generadas': 'Meetings booked',
    'Marcadas con «Reunión conseguida» en el Inbox o el CRM': 'Marked as "Meeting booked" from the Inbox or the CRM',
    'Contactos en secuencia': 'Contacts in sequence',
    'Guarda tu primera lista para empezar': 'Save your first list to get started',
    'Open rate emails': 'Email open rate',
    'Disponible al activar cadencias': 'Available once cadences are active',
    'Score del equipo': 'Team score',
    'Se genera con el Meeting Coach': 'Generated by the Meeting Coach',
    // Dashboard — gráficas y áreas
    'Pipeline generado por semana': 'Pipeline generated per week',
    'Canales activos': 'Active channels',
    'Aún no hay actividad que graficar': 'No activity to chart yet',
    'Cuando tus secuencias empiecen a enviar, aquí verás emails, respuestas y reuniones por semana.': 'Once your sequences start sending, you will see emails, replies and meetings per week here.',
    'Sin canales activos': 'No active channels',
    'Activa tu primera cadencia para ver la distribución por canal.': 'Activate your first cadence to see the split by channel.',
    'Informes diarios, señales y amenazas generados por tus agentes.': 'Daily reports, signals and threats generated by your agents.',
    'Abrir el hub →': 'Open the hub →',
    'Define tu ICP, busca contactos en Apollo y lanza cadencias multi-canal.': 'Define your ICP, find contacts in Apollo and launch multi-channel cadences.',
    'Configurar prospección →': 'Set up prospecting →',
    'Coach en vivo durante tus llamadas y reportes por SDR al terminar.': 'Live coach during your calls and per-SDR reports afterwards.',
    'Iniciar una sesión →': 'Start a session →',
    'Pipeline activo': 'Active pipeline',
    'Ver todo →': 'View all →',
    'Tu pipeline está vacío': 'Your pipeline is empty',
    'Los prospectos que respondan a tus cadencias aparecerán aquí, organizados por etapa.': 'Prospects who reply to your cadences will appear here, organized by stage.',
    'Buscar contactos': 'Find contacts',
    '+ Nueva campaña': '+ New campaign',
    // Market Intelligence
    'Market Intelligence': 'Market Intelligence',
    'Contexto de tu empresa': 'Your company context',
    'Intelligence Hub': 'Intelligence Hub',
    'Global context': 'Global context',
    'Transforma datos de mercado en ventaja competitiva': 'Transform market data into competitive advantage',
    'Actualizar': 'Refresh',
    '+ Completar Matriz': '+ Complete Matrix',
    'Inteligencia que se vuelve acción.': 'Intelligence that becomes action.',
    'No es un resumen de newsletters: es inteligencia accionable sobre tu go-to-market, tu producto, tu consumidor y las ventajas competitivas que puedes explotar en tu próxima prospección.': 'It\'s not a newsletter summary: it\'s actionable intelligence about your go-to-market, your product, your consumer and the competitive advantages you can exploit in your next prospecting.',
    'Competidores monitoreados': 'Monitored competitors',
    'Agrégalos en tu Matriz de Input': 'Add them to your Input Matrix',
    'Señales de mercado': 'Market signals',
    'Se detectan con el Hub activo': 'Detected when Hub is active',
    'Insights accionables': 'Actionable insights',
    'Generados por tus agentes': 'Generated by your agents',
    'Matriz completada': 'Matrix completed',
    'Complétala para activar la IA': 'Complete it to activate AI',
    'Completar / Revisar Matriz de Input': 'Complete / Review Input Matrix',
    'Ver Intelligence Hub': 'View Intelligence Hub',
    'Ver Accionables GTM': 'View GTM Actionables',
    'Monitor de Competidores': 'Competitor Monitor',
    'Sin competidores monitoreados': 'No monitored competitors',
    'Agrega tus competidores en la Matriz de Input y tus agentes empezarán a vigilar sus movimientos.': 'Add your competitors to the Input Matrix and your agents will start monitoring their moves.',
    'Ir al Intelligence Hub': 'Go to Intelligence Hub',
    'Matriz de Input': 'Input Matrix',
    'Define el contexto para que la IA genere inteligencia relevante': 'Define the context so AI generates relevant intelligence',
    'Analizar con IA': 'Analyze with AI',
    'Tu empresa': 'Your company',
    'Competidores': 'Competitors',
    'Mercado': 'Market',
    'Consumidor': 'Consumer',
    'Distribución': 'Distribution',
    'Paso 1: Tu Empresa': 'Step 1: Your Company',
    'Nombre de la empresa': 'Company name',
    'Sitio web': 'Website',
    'Industria / categoría': 'Industry / category',
    'SaaS / Revenue Operations': 'SaaS / Revenue Operations',
    'SaaS / Sales Enablement': 'SaaS / Sales Enablement',
    'SaaS / Marketing Tech': 'SaaS / Marketing Tech',
    'Consultoría': 'Consulting',
    'Agencia': 'Agency',
    'Otro': 'Other',
    'Tamaño del equipo': 'Team size',
    // Prospección
    'Búsqueda': 'Search',
    'Listas': 'Lists',
    'Cadencias': 'Cadences',
    // Ajustes — encabezados
    'Tu informacion personal y de cuenta': 'Your personal and account information',
    'Perfil': 'Profile',
    'Tu informacion personal visible en la plataforma.': 'Your personal information, visible across the platform.',
    'Empresa': 'Company',
    'Nombre completo': 'Full name',
    'Rol': 'Role',
    'Seguridad y cuenta': 'Security & account',
    'Guardar cambios': 'Save changes',
    'Guardar empresa': 'Save company',
    // Ventas AI
    'Iniciar sesión': 'Start session',
    'Preparar reunión con el coach': 'Prepare meeting with coach',
    'Resultados': 'Results',
    'Informes': 'Reports',
    // Common buttons/actions
    'Guardar': 'Save',
    'Cancelar': 'Cancel',
    'Eliminar': 'Delete',
    'Editar': 'Edit',
    'Crear': 'Create',
    'Enviar': 'Send',
    'Descargar': 'Download',
    'Cargar': 'Load',
    'Buscar': 'Search',
    'Filtrar': 'Filter',
    'Limpiar': 'Clear',
    'Aplicar': 'Apply',
    'Cerrar': 'Close',
    'Atrás': 'Back',
    'Siguiente': 'Next',
    'Anterior': 'Previous',
    'Más': 'More',
    'Menos': 'Less',
    'Sí': 'Yes',
    'No': 'No',
    'Aceptar': 'Accept',
    'Rechazar': 'Reject',
    'Confirmar': 'Confirm',
    'Deshacer': 'Undo',
    'Rehacer': 'Redo',
  };

  var EN_ES = {};
  Object.keys(ES_EN).forEach(function (k) { EN_ES[ES_EN[k]] = k; });

  function currentLang() {
    try { return localStorage.getItem(LS_KEY) === 'en' ? 'en' : 'es'; } catch (e) { return 'es'; }
  }

  function translateTextNodes(root, dict) {
    var walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, null);
    var node;
    while ((node = walker.nextNode())) {
      var raw = node.nodeValue;
      if (!raw) continue;
      var trimmed = raw.trim();
      if (!trimmed || !(trimmed in dict)) continue;
      node.nodeValue = raw.replace(trimmed, dict[trimmed]);
    }
  }

  function translateAttrs(root, dict) {
    var els = root.querySelectorAll('[placeholder], [title], [aria-label], [data-placeholder]');
    Array.prototype.forEach.call(els, function (el) {
      ['placeholder', 'title', 'aria-label'].forEach(function (a) {
        var v = el.getAttribute(a);
        if (v && dict[v.trim()]) el.setAttribute(a, dict[v.trim()]);
      });
    });
  }

  function apply() {
    if (currentLang() !== 'en') return;
    var dict = ES_EN;
    translateTextNodes(document.body, dict);
    translateAttrs(document.body, dict);
    paintToggle();
  }

  function setLang(lang) {
    var clean = lang === 'en' ? 'en' : 'es';
    try { localStorage.setItem(LS_KEY, clean); } catch (e) { /* modo privado */ }
    apply();
  }

  function paintToggle() {
    var host = document.getElementById('lang-toggle');
    if (!host) return;
    var lang = currentLang();
    Array.prototype.forEach.call(host.querySelectorAll('[data-lang]'), function (b) {
      b.classList.toggle('on', b.getAttribute('data-lang') === lang);
    });
  }

  function wireToggle() {
    var host = document.getElementById('lang-toggle');
    if (!host || host.dataset.wired) return;
    host.dataset.wired = '1';
    Array.prototype.forEach.call(host.querySelectorAll('[data-lang]'), function (b) {
      b.addEventListener('click', function () { setLang(b.getAttribute('data-lang')); });
    });
    paintToggle();
  }

  function startObserver() {
    if (observer) return;
    observer = new MutationObserver(function () {
      if (currentLang() === 'en') {
        setTimeout(apply, 16);
      }
    });
    observer.observe(document.body, {
      childList: true,
      subtree: true,
      characterData: false,
      attributeFilter: ['placeholder', 'title', 'aria-label']
    });
  }

  function stopObserver() {
    if (observer) {
      observer.disconnect();
      observer = null;
    }
  }

  function init() {
    wireToggle();
    startObserver();
    if (currentLang() === 'en') apply();
  }

  window.i18n = { get: currentLang, set: setLang, apply: apply };

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
  else init();
})();
