/**
 * js/i18n.js — Interruptor de idioma ES/EN para toda la interfaz
 * ─────────────────────────────────────────────────────────────────────────────
 * Traduce TODO el contenido de la app (chrome + vistas profundas) mediante un
 * diccionario de strings exactos. El español es el idioma fuente; en EN se
 * reemplazan los nodos de texto cuyo contenido coincide con el diccionario.
 *
 * Usar MutationObserver para detectar cambios dinámicos y re-aplicar la
 * traducción automáticamente cuando el contenido cambia.
 *
 * API pública: window.i18n = { get(), set(lang), apply() }
 */
(function () {
  'use strict';

  var LS_KEY = 'predictable_lang';
  var observer = null;

  // Diccionario ES → EN (toda la interfaz, strings exactos tras trim).
  var ES_EN = {
    // Sidebar — secciones
    'Operar': 'Operate',
    'Inteligencia': 'Intelligence',
    'Ejecutar': 'Execute',
    'Aprender': 'Learn',
    // Sidebar — items
    'Dashboard': 'Dashboard',
    'Radar': 'Radar',
    'Clients': 'Clients',
    'Prospección': 'Prospecting',
    'Search People': 'Search People',
    'Listas guardadas': 'Saved lists',
    'Contactos': 'Contacts',
    'Secuencias': 'Sequences',
    'Generador de mensajes IA': 'AI message generator',
    'Bandeja': 'Inbox',
    'Inbox WhatsApp': 'WhatsApp Inbox',
    'Plantillas': 'Templates',
    'Ventas AI': 'Sales AI',
    'Meeting Coach': 'Meeting Coach',
    'Reportes': 'Reports',
    'Mi rendimiento': 'My performance',
    // Sidebar — footer
    'Primeros pasos': 'Getting started',
    'Claro': 'Light',
    'Oscuro': 'Dark',
    'ES · Español': 'ES · Spanish',
    'EN · English': 'EN · English',
    'Ajustes': 'Settings',
    'Cerrar sesión': 'Log out',
    // Dashboard
    'Revenue OS': 'Revenue OS',
    'Tu operación de revenue, en un vistazo': 'Your revenue operation, at a glance',
    // Dashboard — KPIs
    'Reuniones generadas': 'Meetings booked',
    'Marcadas con «Reunión conseguida» en el Inbox o el CRM': 'Marked as "Meeting booked" from the Inbox or the CRM',
    'Contactos en secuencia': 'Contacts in sequence',
    'Guarda tu primera lista para empezar': 'Save your first list to get started',
    'Open rate emails': 'Email open rate',
    'Disponible al activar cadencias': 'Available once cadences are active',
    'Score del equipo': 'Team score',
    'Se genera con el Meeting Coach': 'Generated by the Meeting Coach',
    // Dashboard — gráficas y áreas
    'Pipeline generado por semana': 'Pipeline generated per week',
    'Canales activos': 'Active channels',
    'Aún no hay actividad que graficar': 'No activity to chart yet',
    'Cuando tus secuencias empiecen a enviar, aquí verás emails, respuestas y reuniones por semana.': 'Once your sequences start sending, you will see emails, replies and meetings per week here.',
    'Sin canales activos': 'No active channels',
    'Activa tu primera cadencia para ver la distribución por canal.': 'Activate your first cadence to see the split by channel.',
    'Informes diarios, señales y amenazas generados por tus agentes.': 'Daily reports, signals and threats generated by your agents.',
    'Abrir el hub →': 'Open the hub →',
    'Define tu ICP, busca contactos en Apollo y lanza cadencias multi-canal.': 'Define your ICP, find contacts in Apollo and launch multi-channel cadences.',
    'Configurar prospección →': 'Set up prospecting →',
    'Coach en vivo durante tus llamadas y reportes por SDR al terminar.': 'Live coach during your calls and per-SDR reports afterwards.',
    'Iniciar una sesión →': 'Start a session →',
    'Pipeline activo': 'Active pipeline',
    'Ver todo →': 'View all →',
    'Tu pipeline está vacío': 'Your pipeline is empty',
    'Los prospectos que respondan a tus cadencias aparecerán aquí, organizados por etapa.': 'Prospects who reply to your cadences will appear here, organized by stage.',
    'Buscar contactos': 'Find contacts',
    '+ Nueva campaña': '+ New campaign',
    // Market Intelligence
    'Market Intelligence': 'Market Intelligence',
    'Contexto de tu empresa': 'Your company context',
    'Intelligence Hub': 'Intelligence Hub',
    'Global context': 'Global context',
    'Transforma datos de mercado en ventaja competitiva': 'Transform market data into competitive advantage',
    'Actualizar': 'Refresh',
    '+ Completar Matriz': '+ Complete Matrix',
    'Inteligencia que se vuelve acción.': 'Intelligence that becomes action.',
    'No es un resumen de newsletters: es inteligencia accionable sobre tu go-to-market, tu producto, tu consumidor y las ventajas competitivas que puedes explotar en tu próxima prospección.': 'It\'s not a newsletter summary: it\'s actionable intelligence about your go-to-market, your product, your consumer and the competitive advantages you can exploit in your next prospecting.',
    'Competidores monitoreados': 'Monitored competitors',
    'Agrégalos en tu Matriz de Input': 'Add them to your Input Matrix',
    'Señales de mercado': 'Market signals',
    'Se detectan con el Hub activo': 'Detected when Hub is active',
    'Insights accionables': 'Actionable insights',
    'Generados por tus agentes': 'Generated by your agents',
    'Matriz completada': 'Matrix completed',
    'Complétala para activar la IA': 'Complete it to activate AI',
    'Completar / Revisar Matriz de Input': 'Complete / Review Input Matrix',
    'Ver Intelligence Hub': 'View Intelligence Hub',
    'Ver Accionables GTM': 'View GTM Actionables',
    'Monitor de Competidores': 'Competitor Monitor',
    'Sin competidores monitoreados': 'No monitored competitors',
    'Agrega tus competidores en la Matriz de Input y tus agentes empezarán a vigilar sus movimientos.': 'Add your competitors to the Input Matrix and your agents will start monitoring their moves.',
    'Ir al Intelligence Hub': 'Go to Intelligence Hub',
    'Matriz de Input': 'Input Matrix',
    'Define el contexto para que la IA genere inteligencia relevante': 'Define the context so AI generates relevant intelligence',
    'Analizar con IA': 'Analyze with AI',
    'Tu empresa': 'Your company',
    'Competidores': 'Competitors',
    'Mercado': 'Market',
    'Consumidor': 'Consumer',
    'Distribución': 'Distribution',
    'Paso 1: Tu Empresa': 'Step 1: Your Company',
    'Nombre de la empresa': 'Company name',
    'Sitio web': 'Website',
    'Industria / categoría': 'Industry / category',
    'SaaS / Revenue Operations': 'SaaS / Revenue Operations',
    'SaaS / Sales Enablement': 'SaaS / Sales Enablement',
    'SaaS / Marketing Tech': 'SaaS / Marketing Tech',
    'Consultoría': 'Consulting',
    'Agencia': 'Agency',
    'Otro': 'Other',
    'Tamaño del equipo': 'Team size',
    // Prospección
    'Búsqueda': 'Search',
    'Listas': 'Lists',
    'Cadencias': 'Cadences',
    // Ajustes — encabezados
    'Tu informacion personal y de cuenta': 'Your personal and account information',
    'Perfil': 'Profile',
    'Tu informacion personal visible en la plataforma.': 'Your personal information, visible across the platform.',
    'Empresa': 'Company',
    'Nombre completo': 'Full name',
    'Rol': 'Role',
    'Seguridad y cuenta': 'Security & account',
    'Guardar cambios': 'Save changes',
    'Guardar empresa': 'Save company',
    // Ventas AI
    'Iniciar sesión': 'Start session',
    'Preparar reunión con el coach': 'Prepare meeting with coach',
    'Resultados': 'Results',
    'Informes': 'Reports',
    // Common buttons/actions
    'Guardar': 'Save',
    'Cancelar': 'Cancel',
    'Eliminar': 'Delete',
    'Editar': 'Edit',
    'Crear': 'Create',
    'Enviar': 'Send',
    'Descargar': 'Download',
    'Cargar': 'Load',
    'Buscar': 'Search',
    'Filtrar': 'Filter',
    'Limpiar': 'Clear',
    'Aplicar': 'Apply',
    'Cerrar': 'Close',
    'Atrás': 'Back',
    'Siguiente': 'Next',
    'Anterior': 'Previous',
    'Más': 'More',
    'Menos': 'Less',
    'Sí': 'Yes',
    'No': 'No',
    'Aceptar': 'Accept',
    'Rechazar': 'Reject',
    'Confirmar': 'Confirm',
    'Deshacer': 'Undo',
    'Rehacer': 'Redo',
    // Additional comprehensive translations
    'Dashboard': 'Dashboard',
    'Radar': 'Radar',
    'Clients': 'Clients',
    'Contexto de tu empresa': 'Your company context',
    'Intelligence Hub': 'Intelligence Hub',
    'Global context': 'Global context',
    'Tema claro': 'Light theme',
    'Tema oscuro': 'Dark theme',
    'Español': 'Spanish',
    'English': 'English',
    'Tu informacion personal y de cuenta': 'Your personal and account information',
    'Accionables GTM': 'Actionable GTM',
    'Inteligencia que se vuelve acción.': 'Intelligence that becomes action.',
    'Ciclo de ventas típico': 'Typical sales cycle',
    'Coaching en vivo durante la llamada y el reporte final de la reunión.': 'Live coaching during the call and final meeting report.',
    'Elige con quién es la reunión para cargar su brief — el coach no inicia sin un lead.': 'Choose who the meeting is with to load their brief — the coach won\'t start without a lead.',
    'El asistente que escucha tu llamada y te dice qué decir, en vivo.': 'The assistant who listens to your call and tells you what to say, live.',
    'Inteligencia de mercado, actualizada por tus agentes': 'Market intelligence, updated by your agents',
    'PESTEL de tu mercado + 5 fuerzas de Porter de tu competencia + tu FODA convertido en un plan CAME — contexto opcional, todo con IA': 'PESTEL of your market + Porter\'s 5 forces of your competition + your SWOT converted into a CAME plan — optional context, all with AI',
    'Qué hacer esta semana para mover el mercado': 'What to do this week to move the market',
    'Tus accionables se generan desde el Intelligence Hub': 'Your actionables are generated from the Intelligence Hub',
    'Cuando tus agentes publiquen los primeros informes, aquí verás recomendaciones de go-to-market, producto y prospección listas para aplicar.': 'When your agents publish the first reports, you\'ll see go-to-market, product, and prospecting recommendations ready to apply.',
    'Meeting coach en vivo y visibilidad total sobre tu equipo': 'Live meeting coach and total visibility over your team',
    'Ver reportes': 'View reports',
    'Iniciar coach en vivo': 'Start live coach',
    'Un copiloto en cada llamada.': 'A copilot on every call.',
    'Entrenado en las mejores técnicas de ventas B2B, entra a tu Meet, Teams o Zoom y guía al vendedor en tiempo real: objeciones, siguiente paso y contexto del prospecto. Al terminar, el director recibe el reporte de cada SDR.': 'Trained in the best B2B sales techniques, it joins your Meet, Teams or Zoom and guides the seller in real time: objections, next steps, and prospect context. When done, the director receives each SDR\'s report.',
    'Reuniones analizadas': 'Meetings analyzed',
    'Inicia tu primera sesión con el coach': 'Start your first session with the coach',
    'Score promedio del equipo': 'Team average score',
    'Se calcula por reunión analizada': 'Calculated per meeting analyzed',
    'Objeción más frecuente': 'Most frequent objection',
    'Detectada automáticamente por la IA': 'Automatically detected by AI',
    'Tasa de avance a propuesta': 'Advance to proposal rate',
    'Disponible con historial de reuniones': 'Available with meeting history',
    'Reuniones de hoy': 'Today\'s meetings',
    'No hay reuniones agendadas hoy': 'No meetings scheduled today',
    'Cuando tus prospectos agenden desde tus cadencias, aparecerán aquí con su contexto listo para el coach.': 'When your prospects book from your sequences, they\'ll appear here with context ready for the coach.',
    'Probar el coach ahora': 'Try coach now',
    'Resumen del equipo': 'Team summary',
    'Ver reporte completo →': 'View full report →',
    'Tu equipo aparecerá aquí': 'Your team will appear here',
    'Cada sesión completada con el Meeting Coach genera el score y las áreas de mejora de cada SDR.': 'Each session completed with Meeting Coach generates each SDR\'s score and improvement areas.',
    'Coach en vivo': 'Live coach',
    'El asistente que escucha tu llamada y te dice qué decir, en vivo.': 'The assistant who listens to your call and tells you what to say, live.',
    'Configuración': 'Configuration',
    '■ Finalizar sesión': '■ End session',
    'MEETING COACH': 'MEETING COACH',
    'Tu copiloto para la próxima reunión': 'Your copilot for the next meeting',
    'Lead de esta reunión': 'Lead for this meeting',
    'Cargando tus leads…': 'Loading your leads…',
    'Aún no tienes leads guardados. Busca prospectos y guárdalos en una lista desde Prospección; aquí podrás elegirlos para la reunión.': 'You don\'t have saved leads yet. Search prospects and save them in a list from Prospecting; here you can choose them for the meeting.',
    'Ir a Prospección →': 'Go to Prospecting →',
    'Iniciar coach': 'Start coach',
    'Ver brief': 'View brief',
    'Captura audio + pantalla': 'Capture audio + screen',
    'Pantalla completa con audio + tu micrófono': 'Full screen with audio + your microphone',
    'IA entiende el contexto': 'AI understands context',
    'ICP, historial, etapa': 'ICP, history, stage',
    'Alertas en <2s': 'Alerts in <2s',
    'Objeción, riesgo, señal': 'Objection, risk, signal',
    'Brief automático': 'Automatic brief',
    'El brief se genera automáticamente cuando inicias una sesión con un prospecto: quién es, por qué le importa y qué riesgos hay en el deal.': 'The brief is generated automatically when you start a session with a prospect: who they are, why it matters, and what risks are in the deal.',
    'GENERANDO BRIEF...': 'GENERATING BRIEF...',
    'QUIÉN': 'WHO',
    'POR QUÉ LE IMPORTA': 'WHY IT MATTERS',
    'RIESGOS': 'RISKS',
    'CÓMO ABRIR': 'HOW TO OPEN',
    'QUÉ PREGUNTAR': 'WHAT TO ASK',
    'SEÑALES A VALIDAR': 'SIGNALS TO VALIDATE',
    'Conectando...': 'Connecting...',
    'Transcripción completa': 'Full transcript',
    'La conversación aparecerá aquí en tiempo real...': 'The conversation will appear here in real time...',
    'Etapa actual': 'Current stage',
    'Próximo paso': 'Next step',
    'Analizando...': 'Analyzing...',
    'Score en vivo': 'Live score',
    'Escucha activa': 'Active listening',
    'Profundización del dolor': 'Pain deepening',
    'Control del ritmo': 'Pace control',
    'Manejo de objeciones': 'Objection handling',
    'Esperando audio...': 'Waiting for audio...',
    'Comparte tu pantalla completa con "Compartir audio del sistema" activado.': 'Share your full screen with "Share system audio" enabled.',
    'Reportes': 'Reports',
    'Tu performance en reuniones de venta': 'Your performance in sales meetings',
    'Mi rendimiento': 'My performance',
    'Equipo': 'Team',
    'Deals perdidos': 'Lost deals',
    'Objeciones': 'Objections',
    'Última reunión': 'Last meeting',
    'Cargando tu historial...': 'Loading your history...',
    'Sin reuniones registradas todavía': 'No meetings recorded yet',
    'Cuando completes sesiones con el AI Coach, tu historial de performance aparecerá aquí.': 'When you complete sessions with the AI Coach, your performance history will appear here.',
    'Score por reunión (historial)': 'Score per meeting (history)',
    'Mis reuniones': 'My meetings',
    'Prospecto': 'Prospect',
    'Fecha': 'Date',
    'Duración': 'Duration',
    'Escucha': 'Listening',
    'Discovery': 'Discovery',
    'Todavía no hay reportes de tu equipo': 'No team reports yet',
    'Cuando tus SDRs completen sesiones con el Meeting Coach, aquí verás sus scores, reuniones y áreas de mejora.': 'When your SDRs complete sessions with Meeting Coach, you\'ll see their scores, meetings, and improvement areas here.',
    'Iniciar una sesión': 'Start a session',
    'Score promedio por SDR': 'Average score per SDR',
    'Meetings por SDR (últimas 4 semanas)': 'Meetings per SDR (last 4 weeks)',
    'Performance detallado del equipo': 'Detailed team performance',
    'Score Avg': 'Score Avg',
    'Deals avanzados': 'Deals advanced',
    'Alerta': 'Alert',
    'Sin deals analizados todavía': 'No deals analyzed yet',
    'La IA detecta por qué y en qué etapa se pierden tus deals a partir de las reuniones analizadas por el coach. Necesitas al menos unas cuantas sesiones para ver patrones.': 'AI detects why and at what stage your deals are lost from coach-analyzed meetings. You need at least a few sessions to see patterns.',
    'Detectadas por la IA en las reuniones analizadas por el coach.': 'Detected by AI in coach-analyzed meetings.',
    'Analizando objeciones...': 'Analyzing objections...',
    'Aún no hay objeciones detectadas': 'No objections detected yet',
    'Esta vista se llena conforme el coach analiza reuniones: cada objeción real queda registrada con su frecuencia, cómo se manejó y la mejor respuesta sugerida.': 'This view fills as the coach analyzes meetings: each real objection is recorded with its frequency, how it was handled, and the best suggested response.',
    'Cargando última reunión...': 'Loading last meeting...',
    'Sin reuniones grabadas todavía': 'No recordings yet',
    'Cuando termines tu primera sesión con el AI Coach, el reporte completo de la reunión aparecerá aquí.': 'When you complete your first session with the AI Coach, the full meeting report will appear here.',
    'ÚLTIMA REUNIÓN': 'LAST MEETING',
    'Lead frío': 'Cold lead',
    'Lead tibio': 'Warm lead',
    'Lead caliente': 'Hot lead',
    'Resumen': 'Summary',
    'Insights clave': 'Key insights',
    'Oportunidad': 'Opportunity',
    'Riesgo': 'Risk',
    'Señal de compra': 'Purchase signal',
    'Dato clave': 'Key fact',
    'Objeciones reales de la reunión': 'Real meeting objections',
    'Superada': 'Overcome',
    'Parcial': 'Partial',
    'No resuelta': 'Unresolved',
    'Cómo se manejó:': 'How it was handled:',
    'Respuesta sugerida:': 'Suggested response:',
    '✓ Lo que hizo bien': '✓ What went well',
    '⚠ Oportunidades perdidas': '⚠ Missed opportunities',
    'Feedback del coach': 'Coach feedback',
    'Fortalezas': 'Strengths',
    'Áreas de mejora': 'Areas of improvement',
    'Consejo principal': 'Main advice',
    'Próximos pasos': 'Next steps',
    'Perfil': 'Profile',
    'Metodo de acceso': 'Access method',
    'Email verificado': 'Email verified',
    'Cuenta creada': 'Account created',
    'Contrasena': 'Password',
    'Enviar email para cambiarla': 'Send email to change it',
    'Te llegara un link a tu email para resetear la contrasena.': 'A link will arrive at your email to reset the password.',
    'Gestión de equipo': 'Team management',
    'Asigna roles a los miembros de tu empresa. Los cambios aplican de inmediato.': 'Assign roles to your company members. Changes apply immediately.',
    'Cargando miembros...': 'Loading members...',
    'No hay otros miembros en tu empresa todavía.': 'No other members in your company yet.',
    'Miembro': 'Member',
    'Zona de peligro': 'Danger zone',
    'Acciones irreversibles. Procede con cuidado.': 'Irreversible actions. Proceed with caution.',
    'Borrar mi cuenta': 'Delete my account',
    'Borrar cuenta permanentemente': 'Delete account permanently',
    'Esto borra tu usuario, tu perfil y todos tus datos. No se puede deshacer.': 'This deletes your user, profile, and all your data. It cannot be undone.',
    '¿Cerrar sesión?': 'Sign out?',
    'Tendrás que volver a iniciar sesión para acceder a tu cuenta.': 'You\'ll have to sign in again to access your account.',
    'Selecciona el lead de esta reunión antes de iniciar el coach.': 'Select the lead for this meeting before starting the coach.',
    'El módulo del coach no cargó. Recarga la página e intenta de nuevo.': 'The coach module didn\'t load. Reload the page and try again.',
  };

  var EN_ES = {};
  Object.keys(ES_EN).forEach(function (k) { EN_ES[ES_EN[k]] = k; });

  function currentLang() {
    try { return localStorage.getItem(LS_KEY) === 'en' ? 'en' : 'es'; } catch (e) { return 'es'; }
  }

  function translateTextNodes(root, dict) {
    var walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, null);
    var node;
    while ((node = walker.nextNode())) {
      var raw = node.nodeValue;
      if (!raw) continue;
      var trimmed = raw.trim();
      if (!trimmed || !(trimmed in dict)) continue;
      node.nodeValue = raw.replace(trimmed, dict[trimmed]);
    }
  }

  function translateAttrs(root, dict) {
    var els = root.querySelectorAll('[placeholder], [title], [aria-label], [data-placeholder]');
    Array.prototype.forEach.call(els, function (el) {
      ['placeholder', 'title', 'aria-label'].forEach(function (a) {
        var v = el.getAttribute(a);
        if (v && dict[v.trim()]) el.setAttribute(a, dict[v.trim()]);
      });
    });
  }

  function apply() {
    if (currentLang() !== 'en') return;
    var dict = ES_EN;
    translateTextNodes(document.body, dict);
    translateAttrs(document.body, dict);
    paintToggle();
  }

  function setLang(lang) {
    var clean = lang === 'en' ? 'en' : 'es';
    try { localStorage.setItem(LS_KEY, clean); } catch (e) { /* modo privado */ }
    apply();
  }

  function paintToggle() {
    var host = document.getElementById('lang-toggle');
    if (!host) return;
    var lang = currentLang();
    Array.prototype.forEach.call(host.querySelectorAll('[data-lang]'), function (b) {
      b.classList.toggle('on', b.getAttribute('data-lang') === lang);
    });
  }

  function wireToggle() {
    var host = document.getElementById('lang-toggle');
    if (!host || host.dataset.wired) return;
    host.dataset.wired = '1';
    Array.prototype.forEach.call(host.querySelectorAll('[data-lang]'), function (b) {
      b.addEventListener('click', function () { setLang(b.getAttribute('data-lang')); });
    });
    paintToggle();
  }

  function startObserver() {
    if (observer) return;
    observer = new MutationObserver(function () {
      if (currentLang() === 'en') {
        setTimeout(apply, 16);
      }
    });
    observer.observe(document.body, {
      childList: true,
      subtree: true,
      characterData: false,
      attributeFilter: ['placeholder', 'title', 'aria-label']
    });
  }

  function stopObserver() {
    if (observer) {
      observer.disconnect();
      observer = null;
    }
  }

  function init() {
    wireToggle();
    startObserver();
    if (currentLang() === 'en') apply();
  }

  window.i18n = { get: currentLang, set: setLang, apply: apply };

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
  else init();
})();
