-- ═══════════════════════════════════════════════════════════════════════════
-- Meeting Coach (bot mode): deferred report finalization.
--
-- In bot mode the transcript comes from Recall.ai, and with the async
-- transcription provider it can land minutes AFTER the SDR ends the session.
-- endMeeting therefore no longer generates the report immediately when the
-- transcript is not there yet: it records ended_at, marks the meeting
-- `processing`, and the report is generated by `finalizeReport` once the
-- full transcript is available (client polls from the Reportes page).
--
--   ended_at          when the SDR ended the session (duration is computed
--                     from this, not from the moment the report was built)
--   transcript_source where the transcript used for the report came from:
--                     webhook | recall_api | local
--
-- status values are now: live | processing | closed | error
--
-- Idempotent and non-destructive.
-- ═══════════════════════════════════════════════════════════════════════════
ALTER TABLE public.coach_meetings
  ADD COLUMN IF NOT EXISTS ended_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS transcript_source TEXT;

CREATE INDEX IF NOT EXISTS coach_meetings_status_idx
  ON public.coach_meetings(status);
